# Dynamics config/checkpoints/data etc
mogpe_config_file = "./scenario_4/configs/subset_mogpe_config.toml"
mogpe_ckpt_dir = "./scenario_4/checkpoints/subset-dataset/2_experts/09-03-150758"
data_path = "./scenario_4/data/npz/subset_full_dataset_3294_samples_42_seed.npz"
desired_expert_num = 1

# Environment config
scenario = "velocity-controlled-point-mass/scenario-4"
num_timesteps = 10
delta_time = 0.05

# Traj opt config
state_dim = 2
control_dim = 2
start_state = [3.0, 2.0]
target_state = [0.0, -2.0]
state_cost_weight = 0.01  # Q = tf.eye(state_dim) * state_cost_weight
terminal_state_cost_weight = 0.01 # Qterminal = tf.eye(state_dim) * terminal_state_cost_weight
control_cost_weight = 0.01 # R = tf.eye(control_dim) * control_cost_weight

# Constraints config
chance_constraints = true
control_constraints = true
chance_constraints_lower_bound = 0.8
chance_constraints_upper_bound = 1.0
velocity_constraints_lower_bound = [-8.0, -8.0]
velocity_constraints_upper_bound = [8.0, 8.0]

# Optimisation config
log_dir = "./logs/traj-opt/mode-remaining/subset-dataset/"
method = "SLSQP" # or "SLSQP" or "L-BFGS-B"
maxiter = 1000
slow_tasks_period = 5
fast_tasks_period = 1
num_ckpts = 5
