class_name: ModeOpt
config:
  start_state: [-1.0, -2.0]
  target_state: [1.7, 3.0]
  env_name: velocity-controlled-point-mass/scenario-7
  dataset: null
  desired_mode: 1
  mode_satisfaction_probability: 0.8
  learning_rate: 0.01
  epsilon: 1.0e-08
  mode_controller: null
  save_freq: 1000  # save model after every save_freq of batches
  log_dir: ./experiments/exploration-prob-0.8/
  dynamics_fit_kwargs: # args to pass to keras model.fit(X, Y, callbacks, **dynamics_fit_kwargs)
    # epochs: 1000
    epochs: 300
    batch_size: 128
    validation_split: null
  dynamics:
    class_name: ModeOptDynamics
    config:
      desired_mode: 1
      mosvgpe:
        class_name: MixtureOfSVGPExperts
        config:
          experts_list:
          - class_name: SVGPExpert
            config:
              kernel:
                class_name: SeparateIndependent
                config:
                  kernels:
                  - class_name: SquaredExponential
                    config:
                      lengthscales: [1.0, 1.0, 1.0, 1.0]
                      variance: 1.0
                  - class_name: SquaredExponential
                    config:
                      lengthscales: [1.0, 1.0, 1.0, 1.0]
                      variance: 1.0
              likelihood:
                class_name: Gaussian
                config:
                  variance: 1.0
              mean_function:
                class_name: Constant
                config:
                  c: 0.0
              inducing_variable:
                class_name: SharedIndependentInducingVariables
                config:
                  inducing_variable:
                    class_name: InducingPoints
                    config:
                      num_inducing: 90
                      input_dim: 4
              num_latent_gps: 2
          - class_name: SVGPExpert
            config:
              kernel:
                class_name: SeparateIndependent
                config:
                  kernels:
                  - class_name: SquaredExponential
                    config:
                      lengthscales: [1.0, 1.0, 1.0, 1.0]
                      variance: 1.0
                  - class_name: SquaredExponential
                    config:
                      lengthscales: [1.0, 1.0, 1.0, 1.0]
                      variance: 1.0
              likelihood:
                class_name: Gaussian
                config:
                  variance: 1.0
              mean_function:
                class_name: Constant
                config:
                  c: 0.0
              inducing_variable:
                class_name: SharedIndependentInducingVariables
                config:
                  inducing_variable:
                    class_name: InducingPoints
                    config:
                      num_inducing: 90
                      input_dim: 4
              num_latent_gps: 2
          gating_network:
            class_name: SVGPGatingNetwork
            config:
              kernel:
                class_name: SquaredExponential
                config:
                  lengthscales: [1.0, 1.0]
                  variance: 1.0
                  active_dims: [0, 1]
              inducing_variable:
                class_name: InducingPoints
                config:
                  num_inducing: 100
                  input_dim: 2
      predict_state_difference: true
      state_dim: 2
